version: "3"
services:
  api:
    build: psycode99/fastapi
    ports:
      - 8000:8080
  
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8080 
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}  # Assuming PostgreSQL service name is "postgres"
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_NAME=${DATABASE_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      - postgres  # Ensure that the FastAPI container starts after the PostgreSQL container
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
