name: Build and Deploy Code

on: [push, pull_request]

env: 
    DATABASE_HOSTNAME: postgres  # Assuming PostgreSQL service name is "postgres"
    DATABASE_PORT: 5432
    DATABASE_PASSWORD: wordpress
    DATABASE_USERNAME: postgres
    DATABASE_NAME: fastapi
    SECRET_KEY: HJ62GkTz9&%y
    ALGORITHM: HS256
    ACCESS_TOKEN_EXPIRE_MINUTES: 30

jobs: 
    job1: 
        runs-on: ubuntu-latest
        steps: 
            - name: pulling git repo
              uses: actions/checkout@v2
            - name: install python version 3.11
              uses: actions/setup-python@v5
              with: 
                python-version: '3.11'
            - name: update pip
              run: python -m pip install --upgrade pip
            - name: installing dependencies
              run: pip install -r requirements.txt
            - name: set up pytest
              run: |
                pip install pytest
                pytest